// GENERATED by scripts/build-product-images.mjs — do not edit.
// Product image key → content hash + dominant colour (see lib/catalog/product-images.ts).
export const PRODUCT_IMAGE_ASSETS = {
  "version": 1,
  "widths": [
    320,
    640,
    960
  ],
  "images": {}
} as const;
